on: [ push ]

jobs:
  lint_job:
    runs-on: ubuntu-latest
    name: Run lint against push
    steps:
      - name: golangci-lint
        id: golangci-lint
        uses: ./.github/actions/lint@master

