on: [ push ]

jobs:
  lint_job:
    runs-on: ubuntu-latest
    name: Run lint against push
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: install deps
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.44.2
      - name: lint
        run: |
          golangci-lint run
